### ISSUE TITLE
Hi,能否更新一下Ubuntu下载链接？

### ISSUE THREAD

**Issue by cn0xroot** [mobile-insight/mobileinsight-dev#4]
如issues/3所说，下载链接404：
https://github.com/mobile-insight/mobileinsight-dev/issues/3#issuecomment-348065479
自己修改成 ubuntu/xenial64 会导致的用户名、系统配置差异，导致项目编译失败。

**Comment by zwyuan** [comment]
Hi, I checked the link on latest commit (423bb38) from Oct 5th, the VM box we are using is `bento/ubuntu-16.04`(https://app.vagrantup.com/bento/boxes/ubuntu-16.04), which is a working link. Can you check if you are using the latest release first? Can you access the link directly: https://app.vagrantup.com/bento/boxes/ubuntu-16.04?

**Comment by cn0xroot** [comment]
刚刚看了一下，是由于执行了 README.md里面的 
```
wget https://github.com/mobile-insight/mobileinsight-dev/archive/v1.0.tar.gz
tar -xf v1.0.tar.gz mobileinsight-dev-1.0/Vagrantfile
mv mobileinsight-dev-1.0/Vagrantfile .
```

命令导致这个错误的。
